# 物品信息模组配置文件
# 包含模组加载所需的数据
# 有几个必需字段 (#mandatory)，还有更多可选字段 (#optional)
# 整体格式是标准 TOML 格式，v0.5.0
# 注意，此文件中有几个 TOML 列表
# 在这里找到关于 toml 格式的更多信息：https://github.com/toml-lang/toml
# 要加载的模组加载器类型名称 - 对于常规 FML @Mod 模组，应该是 javafml
modLoader = "javafml" #mandatory
# 要匹配的加载器版本范围 - 对于常规 FML @Mod，将是 forge 版本
loaderVersion = "[47,)" #mandatory 这通常在每个 Minecraft 版本中由 Forge 提升。请在我们的下载页面查看版本列表。
# 你的模组许可证。这是必需的元数据，可更轻松地理解你的再分发属性。
# 在 https://choosealicense.com/ 查看你的选项。所有权利保留是默认的版权立场，因此是这里的默认值。
license = "GNU GPLV3"
# 当出现问题时，让人们参考的 URL
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
# 模组列表 - 允许的数量由各个模组加载器决定
[[mods]] #mandatory
# 模组的 modid
modId = "item_info_mod" #mandatory
# 模组的版本号
version = "1.0.1" #mandatory
# 模组的显示名称
displayName = "item_info_mod" #mandatory
# 查询此模组更新的 URL。查看 JSON 更新规范 https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# 模组的 "主页" URL，在模组 UI 中显示
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# 文件名（在模组 JAR 根目录）包含用于显示的徽标
#logoFile="item_info_mod.png" #optional
# 在模组 UI 中显示的文本字段
#credits="Thanks for this example mod goes to Java" #optional
# 在模组 UI 中显示的文本字段
authors = "biantwin" #optional
# 显示测试控制你的模组在服务器连接屏幕上的显示
# MATCH_VERSION 意味着如果客户端和服务器版本不同，你的模组将导致红色 X。这是默认行为，如果你的模组有服务端和客户端元素，应该选择此选项。
# IGNORE_SERVER_VERSION 意味着如果模组在服务端存在但在客户端不存在，不会导致红色 X。如果你是仅服务端模组，应该使用此选项。
# IGNORE_ALL_VERSION 意味着如果模组在客户端或服务端存在，不会导致红色 X。这是一个特殊情况，只有当你的模组没有服务端组件时才应使用。
# NONE 意味着你的模组上没有设置显示测试。你需要自己处理，参见 IExtensionPoint.DisplayTest 获取更多信息。你可以用此值定义任何你想要的方案。
# 重要说明：这不是关于你的模组在哪个环境（客户端或专用服务端）加载的指令。你的模组应该在它找到自己的任何地方加载（并且可能什么都不做！）
displayTest="IGNORE_SERVER_VERSION" # MATCH_VERSION 是未指定时的默认值 (#optional)

# 模组的描述文本（多行！）(#mandatory)
description = '''biantwin's mod'''
# 依赖项 - 使用 . 来表示特定 modid 的依赖。依赖是可选的。
[[dependencies.item_info_mod]] #optional
# 依赖的 modid
modId = "forge" #mandatory
# 这个依赖是否必须存在 - 如果不存在，必须指定下面的排序
mandatory = true #mandatory
# 依赖的版本范围
versionRange = "[47,)" #mandatory
# 依赖的排序关系 - 如果依赖不是强制的，需要 BEFORE 或 AFTER
# BEFORE - 此模组在依赖之前加载
# AFTER - 此模组在依赖之后加载
ordering = "NONE"
# 依赖应用的端 - BOTH, CLIENT, 或 SERVER
side = "BOTH"# 另一个依赖
[[dependencies.item_info_mod]]
modId = "minecraft"
mandatory = true
# 此版本范围声明了从当前 minecraft 版本到但不包括下一个主要版本的最小值
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
